Repository eatda/eatda-fe, pull requests merged in 2023-01, with the labels that each got.

#5 feat : miniHeader 추가
  public/img/back.svg
  public/img/home.svg
  public/img/home_empty.svg
  public/img/kitchen.svg
  public/img/kitchen_empty.svg
  public/img/library.svg
  public/img/library_empty.svg
  src/components/common/Header.tsx
  src/components/common/MiniHeader.tsx
  src/components/common/Navigation.tsx
  src/components/layout/Layout.tsx
  src/components/layout/TabBar.tsx
  src/components/recipe/RecipeCard.tsx
  src/components/recipe/RecipeList.tsx
  src/components/record/RecordCard.tsx
  src/pages/_app.tsx
  src/pages/kitchen/filter.tsx
  src/pages/kitchen/index.tsx
  src/pages/kitchen/ourpick.tsx
  src/pages/library/add.tsx
  src/pages/library/index.tsx
  src/pages/library/report.tsx
  src/pages/record/index.tsx
Labels: 주방 🍳, 서재 📝

#7 feat : 문자열에서 특정 단어만 하이라이트하기 + 이미지에셋 리팩토링
  public/button/back.svg
  public/button/heart_full.svg
  public/tabbar/home.svg
  public/tabbar/home_empty.svg
  public/tabbar/kitchen.svg
  public/tabbar/kitchen_empty.svg
  public/tabbar/library.svg
  public/tabbar/library_empty.svg
  src/assets/imagePath.tsx
  src/components/layout/TabBar.tsx
  src/components/recipe/RecipeCard.tsx
  src/pages/kitchen/detail/[recipeId].tsx
  src/pages/kitchen/process/[recipeId].tsx
  src/store/store.tsx
Labels: 주방 🍳

#8 feat : 카카오 소셜로그인 구현
  .gitignore
  package-lock.json
  package.json
  src/pages/_app.tsx
  src/pages/api/auth/[...nextauth].ts
  src/pages/index.tsx
  src/pages/signup/index.tsx
Labels: 로그인 💬

#10 feat : 홈 뷰 (feat. react-slick, slick-carousel)
  package-lock.json
  package.json
  src/components/home/MealCard.tsx
  src/components/home/SugarCard.tsx
  src/components/layout/TabBar.tsx
  src/pages/home/index.tsx
Labels: 홈 🏠

#9 /signup/create-place 수정 중
  src/pages/kitchen/ourpick.tsx
  src/pages/signup/create-place.tsx
  src/pages/signup/index.tsx
  src/pages/signup/survey.tsx
Labels: 로그인 💬

#13 feat : 레시피 상세보기 조리과정 뷰 Carousel 적용
  next.config.js
  src/components/layout/TabBar.tsx
  src/components/recipe/ProcessCard.tsx
  src/pages/home/index.tsx
  src/pages/kitchen/process/[recipeId].tsx
Labels: 주방 🍳

#12 feat : nickname input 추가
  src/components/common/Button.tsx
  src/pages/signup/create-place.tsx
  src/pages/signup/enter-place.tsx
  src/pages/signup/index.tsx
  src/pages/signup/loading.tsx
  src/pages/signup/survey.tsx
Labels: 로그인 💬

#14 feat : 필터 뷰 다중선택 구현
  next.config.js
  src/components/filter/FilterButton.tsx
  src/components/layout/Layout.tsx
  src/pages/kitchen/filter.tsx
Labels: 주방 🍳

#15 소셜 로그인에서 회원가입 넘어가는 경로 테스트중입니다!
  next.config.js
  package-lock.json
  package.json
  public/character/ch_1.svg
  public/character/ch_2.svg
  public/character/ch_3.svg
  public/character/ch_4.svg
  public/character/ch_5.svg
  src/components/common/Button.tsx
  src/pages/_app.tsx
  src/pages/api/auth/[...nextauth].ts
  src/pages/index.tsx
  src/pages/onboarding/index.tsx
  src/pages/signup/create-place.tsx
  src/pages/signup/index.tsx
  src/pages/signup/loading.tsx
  src/pages/signup/survey.tsx
  src/store/store.tsx
  src/store/surveySlice.tsx
  src/store/userSlice.tsx
Labels: 로그인 💬

#21 feat : 필터 기능 구현
  src/components/filter/FilterButton.tsx
  src/components/recipe/RecipeCard.tsx
  src/pages/kitchen/filter.tsx
  src/pages/kitchen/index.tsx
  src/pages/kitchen/ourpick.tsx
  src/pages/onboarding/index.tsx
  src/pages/signup/enter-place.tsx
  src/pages/signup/loading.tsx
  src/pages/signup/survey.tsx
  src/store/filterSlice.tsx
  src/store/store.tsx
Labels: 주방 🍳, 필터 🗃

#22 feat : 식후 혈당 기록하기 플로우 기능 구현 및 서버 연결
  src/components/common/MiniHeader.tsx
  src/components/common/PushPageButton.tsx
  src/components/layout/Layout.tsx
  src/components/record/RecordCard.tsx
  src/hooks/Fetch.tsx
  src/pages/kitchen/filter.tsx
  src/pages/kitchen/index.tsx
  src/pages/library/add.tsx
  src/pages/library/index.tsx
  src/pages/library/report.tsx
  styles.tsx
Labels: 서재 📝, 혈당기록 🩸

#24 feat : 레시피 상세보기 페이지 api 연결 및 기능 구현 및 디자인 작업
  src/components/kitchen/DetailBox.tsx
  src/components/kitchen/ProcessCard.tsx
  src/components/recipe/ProcessCard.tsx
  src/interface/recipe.ts
  src/pages/kitchen/detail/[recipeId].tsx
  src/pages/kitchen/index.tsx
  src/pages/kitchen/process/[recipeId].tsx
  src/pages/library/index.tsx
Labels: 주방 🍳, 레시피 🥘

#25 design : 전체적인 디자인 점검 및 오류 수정
  src/components/common/FooterButton.tsx
  src/components/common/MiniHeader.tsx
  src/components/common/Navigation.tsx
  src/components/kitchen/RecipeCard.tsx
  src/components/kitchen/RecipeList.tsx
  src/components/layout/Layout.tsx
  src/components/recipe/RecipeList.tsx
  src/hooks/CopyClipBoard.tsx
  src/pages/home/index.tsx
  src/pages/home/mypage.tsx
  src/pages/kitchen/detail/[recipeId].tsx
  src/pages/kitchen/filter.tsx
  src/pages/kitchen/index.tsx
  src/pages/kitchen/ourpick.tsx
  src/pages/kitchen/process/[recipeId].tsx
  src/pages/library/add.tsx
  src/pages/library/index.tsx
  src/pages/library/report.tsx
  src/pages/onboarding/index.tsx
  src/pages/signup/create-place.tsx
  src/pages/signup/enter-place.tsx
  src/pages/signup/index.tsx
  src/pages/signup/survey.tsx
Labels: 주방 🍳, 로그인 💬

#33 feat : 주방 탭 디자인 최종
  public/process/breakfast_black.svg
  public/process/breakfast_white.svg
  public/process/complete_meal.svg
  public/process/dinner_black.svg
  public/process/dinner_white.svg
  public/process/lunch_black.svg
  public/process/lunch_white.svg
  public/process/when_eat.svg
  src/components/common/Navigation.tsx
  src/pages/kitchen/detail/[recipeId].tsx
  src/pages/kitchen/process/[recipeId].tsx
  src/pages/library/add.tsx
  src/pages/library/index.tsx
  src/pages/library/report.tsx
  styles.tsx
Labels: 주방 🍳, 레시피 🥘
